name: Upload to Google Drive

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        run: |
          # Replace the URL with the actual URL of your artifact
          curl -LO https://github.com/TeunTycho/Report/suites/14734757435/artifacts/838540820

      - name: Upload to Google Drive
        uses: dawidd6/action-upload-to-drive@v2
        with:
          file: 838540820  # Replace this with the actual filename of the downloaded artifact

        env:
          CREDENTIALS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
