name: Fetch Issues from itms and devops

on:
  push:
    branches:
      - main  # Pas de taknaam aan indien nodig

jobs:
  fetch-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch issues from itms
        run: |
          owner="forus"
          repo="itms"
          labels="bug,incident"
          url="https://api.github.com/repos/$owner/$repo/issues?labels=$labels"
          response=$(curl -s $url)
          echo "$response" > itms_issues.json

      - name: Fetch issues from devops
        run: |
          owner="forus"
          repo="devops"
          labels="bug,incident"
          url="https://api.github.com/repos/$owner/$repo/issues?labels=$labels"
          response=$(curl -s $url)
          echo "$response" > devops_issues.json

      - name: Upload itms issues as artifact
        uses: actions/upload-artifact@v2
        with:
          name: itms_issues
          path: itms_issues.json

      - name: Upload devops issues as artifact
        uses: actions/upload-artifact@v2
        with:
          name: devops_issues
          path: devops_issues.json
