name: Generate Incident Report

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Add this section to enable manual workflow runs

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch incident issues from Report repository
        run: |
          owner="TeunTycho"
          repo1="Report"
          repo2="ITSM"
          label="incident"
          url1="https://api.github.com/repos/$owner/$repo1/issues?labels=$label"
          url2="https://api.github.com/repos/$owner/$repo2/issues?labels=$label"
          response1=$(curl -s $url1)
          response2=$(curl -s $url2)
          echo "$response1" > issues_report.json
          echo "$response2" > issues_itsm.json
      - name: Combine issue data
        run: |
          cat issues_report.json issues_itsm.json > combined_issues.json
     - name: Generate report
  run: |
    echo "Issue_Number,Title,URL,State,Labels,Assignees,Created_Date,Last_Updated_Date,Closed_Date,Author,Body,Comments,Milestone,Project,Repository,Priority,Related Issues,Affected Systems,Resolution Details,Incident Category,Incident Owner,Time to Resolution,Incident Impact,Root Cause,Status Change History,Tags" > incident_report.csv
    cat combined_issues.json | jq -r '.[] | [.number, .title, .html_url, .state, (.labels | map(.name) | join(", ")), (.assignees | map(.login) | join(", ")), .created_at, .updated_at, .closed_at, .user.login, .body, .comments, (.milestone.title // ""), (.project.name // ""), (.repository.name // ""), "","", "", "", "", "", "", "", ""] | @csv' >> incident_report.csv

   - name: Upload report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: incident_report
          path: incident_report.csv
