name: Fetch Issues from itsm and devops

on:
  push:
    branches:
      - main  # Pas de taknaam aan indien nodig

jobs:
  fetch-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests
          pip install pandas

      - name: Fetch issues from itsm
        run: |
          owner="teuntycho"
          repo="itsm"
          labels="bug,incident"
          url="https://api.github.com/repos/$owner/$repo/issues?labels=$labels"
          response=$(curl -s $url)
          echo "$response" > itsm_issues.json

      - name: Fetch issues from devops
        run: |
          owner="teuntycho"
          repo="devops"
          labels="bug,incident"
          url="https://api.github.com/repos/$owner/$repo/issues?labels=$labels"
          response=$(curl -s $url)
          echo "$response" > devops_issues.json

      - name: Convert JSON to Excel (itsm)
        run: |
          python - <<EOF
          import json
          import pandas as pd

          with open('itsm_issues.json') as f:
              issues = json.load(f)

          df = pd.DataFrame(issues)
          df.to_excel('itsm_issues.xlsx', index=False)
          EOF

      - name: Convert JSON to Excel (devops)
        run: |
          python - <<EOF
          import json
          import pandas as pd

          with open('devops_issues.json') as f:
              issues = json.load(f)

          df = pd.DataFrame(issues)
          df.to_excel('devops_issues.xlsx', index=False)
          EOF

      - name: Upload itsm issues Excel file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: itsm_issues
          path: itsm_issues.xlsx

      - name: Upload devops issues Excel file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: devops_issues
          path: devops_issues.xlsx
