name: Move CSV to Security Repo

on:
  workflow_run:
    workflows: ["Generate Incident Report"]
    branches:
      - main
    types:
      - completed

jobs:
  move-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Download incident_report.csv
        uses: actions/download-artifact@v2
        with:
          name: incident_report
          path: incident_report.csv

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone security repository
        run: |
          git clone https://github.com/TeunTycho/Security.git security_repo

      - name: Move CSV to Security repo
        run: |
          mv incident_report.csv security_repo/

      - name: Commit and push to Security repo
        run: |
          cd security_repo
          git add incident_report.csv
          git commit -m "Update incident report CSV"
          git push origin main
