name: Move Incident Report

on:
  repository_dispatch:
    types:
      - move_incident_report

jobs:
  move-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download incident_report.csv from Report repository
        run: |
          owner="TeunTycho"
          repo="Report"
          artifact_name="incident_report"
          token="${{ secrets.REPORT_REPO_PAT }}"

          artifact_url=$(curl -s -H "Authorization: token $token" "https://api.github.com/repos/$owner/$repo/actions/artifacts?name=$artifact_name" | jq -r '.artifacts[0].archive_download_url')

          curl -s -L -H "Authorization: token $token" -o incident_report.zip "$artifact_url"
          unzip -o incident_report.zip
          rm incident_report.zip

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Move CSV to Security repository
        run: |
          mv incident_report/incident_report.csv .

      - name: Commit and push to Security repository
        run: |
          git add incident_report.csv
          git commit -m "Update incident report CSV"
          git push origin main
