name: Move Incident Report

on:
  workflow_dispatch:

jobs:
  move_incident_report:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Move Report Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_TOKEN }}  # Replace 'GH_TOKEN' with the correct secret name
          repository: TeunTycho/Report
          event-type: move_incident_report
          client-payload: {}
